services:

  frontend:
    build: ./frontend

    container_name: pristine-frontend

    ports:
      - "80:80"

    depends_on:
      - backend

  backend:
    build: ./backend

    container_name: pristine-backend

    ports:
      - "5000:5000"

  postgres:
    image: postgres:15